### ISSUE TITLE
Handling of Floating user balances

### ISSUE THREAD

**Issue by sachindkagrawal15** [yAudit/summa-solvency#22]
Handling of Floating user balances

Throughout Summa Protocol, it seems that the balances are handled by BigInt type. However, in real life, for any Cryptocurrency like ETH, etc , user can be a floating point also. 

The handling of floating point balances seems missing (Please correct me if I have overlooked something). If it is missing, then handling of floating point balances should be implemented.

**Comment by 0xalizk** [comment]
Cryptocurrencies are specified and implemented as positive integers (typically as type `uint` to save on bits because we don't need to worry about negative balances) and the floating point representation is just UI thing.
